CREATE TABLE `goods` (
  `id` int PRIMARY KEY AUTO_INCREMENT,
  `package_no` varchar(100) DEFAULT NULL,
  `package_descrip` varchar(255) DEFAULT NULL,
  `unit` varchar(50) DEFAULT NULL,
  `quantity` varchar(50) DEFAULT NULL,
  `procuement_type` varchar(100) DEFAULT NULL,
  `tender_approval` varchar(100) DEFAULT NULL,
  `source_funds` varchar(100) DEFAULT NULL,
  `cost_lac` double UNSIGNED DEFAULT NULL,
  `invitation_tender` DATE,
  `signing_contract` DATE,
  `conpletion_contract` DATE,
  `procurement_status` varchar(255) DEFAULT NULL,
  `created_at` datetime default current_timestamp,
  `updated_at` datetime default current_timestamp
)


CREATE TABLE `works` (
  `id` int PRIMARY KEY AUTO_INCREMENT,
  `package_no` varchar(100) DEFAULT NULL,
  `package_descrip` varchar(255) DEFAULT NULL,
  `unit` varchar(50) DEFAULT NULL,
  `quantity` varchar(50) DEFAULT NULL,
  `procuement_type1` varchar(100) DEFAULT NULL,
  `procuement_type2` varchar(100) DEFAULT NULL,
  `procuement_type3` varchar(100) DEFAULT NULL,
  `tender_approval1` varchar(100) DEFAULT NULL,
  `tender_approval2` varchar(100) DEFAULT NULL,
  `tender_approval3` varchar(100) DEFAULT NULL,
  `source_funds1` varchar(100) DEFAULT NULL,
  `source_funds2` varchar(100) DEFAULT NULL,
  `source_funds3` varchar(100) DEFAULT NULL,
  `cost_lac1` double UNSIGNED DEFAULT NULL,
  `cost_lac2` double UNSIGNED DEFAULT NULL,
  `cost_lac3` double UNSIGNED DEFAULT NULL,
  `invitation_prequalific1` DATE,
  `invitation_prequalific2` DATE,
  `invitation_prequalific3` DATE,
  `invitation_tender1` DATE,
  `invitation_tender2` DATE,
  `invitation_tender3` DATE,
  `signing_contract1` DATE,
  `signing_contract2` DATE,
  `signing_contract3` DATE,
  `conpletion_contract1` DATE,
  `conpletion_contract2` DATE,
  `conpletion_contract3` DATE,
  `conpletion_date` DATE,
  `name_address` varchar(255) DEFAULT NULL,
  `firm_focal` varchar(255) DEFAULT NULL,
  `paid_date` DATE,
  `financial_progress` varchar(255) DEFAULT NULL,
  `physical progress` varchar(255) DEFAULT NULL,
  `created_at` datetime default current_timestamp,
  `updated_at` datetime default current_timestamp
)



CREATE TABLE `services` (
  `id` int PRIMARY KEY AUTO_INCREMENT,
  `package_no` varchar(100) DEFAULT NULL,
  `package_descrip` varchar(255) DEFAULT NULL,
  `unit` varchar(50) DEFAULT NULL,
  `quantity` varchar(50) DEFAULT NULL,
  `procuement_type` varchar(100) DEFAULT NULL,
  `tender_approval` varchar(100) DEFAULT NULL,
  `source_funds` varchar(100) DEFAULT NULL,
  `cost_lac` double UNSIGNED DEFAULT NULL,
  `invitation_eoi` DATE,
  `issue_rep` DATE,
  `signing_contract` DATE,
  `conpletion_contract` DATE,
  `procurement_status` varchar(255) DEFAULT NULL,
  `created_at` datetime default current_timestamp,
  `updated_at` datetime default current_timestamp
)